version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=chifoumi
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - chifoumi-network
    command: mongod --auth

  api:
    build:
      context: ./functions
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URL=mongodb://root:password123@mongodb:27017/chifoumi?authSource=admin
      - SECRET_KEY=your-secret-key-change-in-production
      - PORT=5001
      - NODE_ENV=development
    env_file:
      - ./functions/.env
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - chifoumi-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - api
    networks:
      - chifoumi-network
    volumes:
      - ./client:/app
      - /app/node_modules
    user: "node"

networks:
  chifoumi-network:
    driver: bridge

volumes:
  mongodb_data:
